version: "3.8"
services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: palpalette
      TZ: Europe/Berlin
      PGTZ: Europe/Berlin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    command: >
      postgres -c timezone=Europe/Berlin

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    environment:
      TZ: Europe/Berlin
    ports:
      - "3000:3000" # HTTP REST API for mobile app
      - "3001:3001" # Raw WebSocket for ESP32 devices only
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /etc/localtime:/etc/localtime:ro

volumes:
  postgres_data:
